# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frame_stream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'frame_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66rame_stream.proto\x12\x0clightmonitor\"\x96\x01\n\x0c\x46rameRequest\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x13\n\x0bstream_name\x18\x02 \x01(\t\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x03\x12\r\n\x05width\x18\x05 \x01(\x05\x12\x0e\n\x06height\x18\x06 \x01(\x05\x12\x15\n\rtarget_labels\x18\x07 \x03(\t\"]\n\x0cPushResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12+\n\ndetections\x18\x03 \x03(\x0b\x32\x17.lightmonitor.Detection\"W\n\tDetection\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\'\n\x04\x62\x62ox\x18\x03 \x01(\x0b\x32\x19.lightmonitor.BoundingBox\"I\n\x0b\x42oundingBox\x12\r\n\x05x_min\x18\x01 \x01(\x02\x12\r\n\x05y_min\x18\x02 \x01(\x02\x12\r\n\x05x_max\x18\x03 \x01(\x02\x12\r\n\x05y_max\x18\x04 \x01(\x02\x32Y\n\x12\x46rameStreamService\x12\x43\n\tPushFrame\x12\x1a.lightmonitor.FrameRequest\x1a\x1a.lightmonitor.PushResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frame_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEREQUEST']._serialized_start=37
  _globals['_FRAMEREQUEST']._serialized_end=187
  _globals['_PUSHRESPONSE']._serialized_start=189
  _globals['_PUSHRESPONSE']._serialized_end=282
  _globals['_DETECTION']._serialized_start=284
  _globals['_DETECTION']._serialized_end=371
  _globals['_BOUNDINGBOX']._serialized_start=373
  _globals['_BOUNDINGBOX']._serialized_end=446
  _globals['_FRAMESTREAMSERVICE']._serialized_start=448
  _globals['_FRAMESTREAMSERVICE']._serialized_end=537
# @@protoc_insertion_point(module_scope)
