# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import frame_stream_pb2 as frame__stream__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in frame_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FrameStreamServiceStub(object):
    """Service for streaming video frames from Monitor to Detection module.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushFrame = channel.unary_unary(
                '/lightmonitor.FrameStreamService/PushFrame',
                request_serializer=frame__stream__pb2.FrameRequest.SerializeToString,
                response_deserializer=frame__stream__pb2.PushResponse.FromString,
                _registered_method=True)


class FrameStreamServiceServicer(object):
    """Service for streaming video frames from Monitor to Detection module.
    """

    def PushFrame(self, request, context):
        """Push a single extracted frame for detection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrameStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.PushFrame,
                    request_deserializer=frame__stream__pb2.FrameRequest.FromString,
                    response_serializer=frame__stream__pb2.PushResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lightmonitor.FrameStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lightmonitor.FrameStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FrameStreamService(object):
    """Service for streaming video frames from Monitor to Detection module.
    """

    @staticmethod
    def PushFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lightmonitor.FrameStreamService/PushFrame',
            frame__stream__pb2.FrameRequest.SerializeToString,
            frame__stream__pb2.PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
